- .eslintrc.js
- .husky/pre-commit
- .husky/pre-push
- .prettierrc.js
- App.tsx
- __tests__/App-test.tsx
- package-lock.json
- package.json
- react-native.config.js
- src/screens/Home.tsx
setting up ESLint, setup husky and adjust it as:
On commit - run linter
On push - run tests
> add: Setup husky and adjust it as:commit and push

- App.tsx
- package-lock.json
- package.json
- src/bll/appReducer.ts
- src/bll/store/store.ts
- src/hooks/hooks.ts
added redux-toolkit, initial setting for redux and hooks useAppSelector, useAppDispatch
> add: redux-toolkit, initial settings, hooks

- .eslintrc.js
- App.tsx
- src/components/Tabs/Tab/index.tsx
- src/components/Tabs/Tab/styles.ts
- src/components/Tabs/index.tsx
- src/components/Tabs/styles.ts
- src/screens/Home.tsx
- ui/colors.ts
create component "Tabs" on Home screen
> add: create component "Tabs" on Home screen

- src/components/Sort/index.tsx
- src/components/Sort/styles.ts
> fix: add selectedRowStyle

- .storybook/Storybook.tsx
- .storybook/main.js
- .storybook/storybook.requires.js
- App.tsx
- src/components/Tabs/story/Tabs.stories.tsx
> Add storybook components

- src/components/ui/CustomTextInput/index.tsx
- src/components/ui/CustomTextInput/styles.ts
- src/components/ui/ReadyStyles/Boxes/Boxes.ts
- src/components/ui/ReadyStyles/Boxes/index.ts
- src/components/ui/ReadyStyles/Containers/index.ts
- src/screens/CreateTest.tsx
> Add 'text input' elements on 'Create test' screen

- ios/Podfile.lock
- package-lock.json
- package.json
- src/components/SwitchSelector/index.tsx
- src/components/SwitchSelector/styles.ts
- src/navigation/navigation.tsx
- src/screens/Home.tsx
- src/types/SwitchSelectjrs-types.ts
> feat: create component SwitchSelectors

- src/components/SwitchSelector/styles.ts
- src/components/ui/AppButton/styles.ts
- src/components/ui/AppSelect/index.tsx
- src/components/ui/ReadyStyles/Containers/index.ts
- src/screens/CreateTest.tsx
- src/screens/Home.tsx
> add element to the TestSettings

- src/components/TimerInput/index.tsx
- src/components/TimerInput/styles.ts
- src/components/TimerInputElement/index.tsx
- src/components/TimerInputElement/styles.ts
- src/screens/CreateTest.tsx
> feat: add timer input

- package-lock.json
- package.json
- src/components/AnswersOptions/tests/AnswersOptions.test.tsx
- src/components/AnswersOptions/tests/__snapshots__/snapshot.test.tsx.snap
- src/components/AnswersOptions/tests/functional.test.tsx
- src/components/AnswersOptions/tests/snapshot.test.tsx
- src/components/QuestionsTabs/index.tsx
- tsconfig.json
> feat: add test on AnswersOptions

- .storybook/storybook.requires.js
- src/components/AnswersOptions/index.tsx
- src/components/AnswersOptions/story/AnswersOptions.stories.tsx
> feat: create AnswersOptions story

- src/bll/quizReducer.ts
- src/components/AddingAnswer/index.tsx
- src/components/DraggableBottomSheet/index.tsx
- src/components/Header/index.tsx
- src/components/IncorrectAnswers/index.tsx
- src/components/IncorrectAnswers/styles.ts
- src/components/Notification/CloseButton/index.tsx
- src/components/ProgressBar/ProgressView/styles.ts
- src/components/QuestionsTabs/QuestionTab/index.tsx
- src/components/QuestionsTabs/QuestionTab/styles.ts
- src/components/QuestionsTabs/index.tsx
- src/components/TestResult/index.tsx
- src/components/TestResult/styles.ts
- src/components/ui/AppButton/index.tsx
- src/components/ui/AppSelect/index.tsx
- src/components/ui/CheckBox/index.tsx
- src/components/ui/CustomTextInput/styles.ts
- src/components/ui/ReadyStyles/Boxes/index.ts
- src/components/ui/ReadyStyles/Containers/index.ts
- src/components/ui/SmallButton/index.tsx
- src/components/ui/SmallButton/styles.ts
- src/customTypes/quiz-types.ts
- src/dal/instance.ts
- src/screens/CreateTest/CreateQuestion/CreateAnswer/index.tsx
- src/screens/CreateTest/CreateQuestion/index.tsx
- src/screens/CreateTest/QuestionsSettings/index.tsx
- src/screens/CreateTest/TestSettings.tsx
- src/theme/colors.ts
Change logic when adding correct answer.
> feat: changing logic when adding correct answer

- __tests__/App-test.tsx
- package-lock.json
- package.json
- src/bll/authReducer.ts
- src/bll/quizReducer.ts
- src/bll/store/store.ts
- src/components/QuestionsTabs/index.tsx
- src/components/ui/Modal/index.tsx
- src/customTypes/quiz-types.ts
- src/customTypes/quizzesAPI-types.ts
- src/dal/authAPI.ts
- src/dal/instance.ts
- src/dal/questionsAPI.ts
- src/dal/quizzesAPI.ts
- src/screens/CreateTest/CreateQuestion/index.tsx
- src/screens/CreateTest/QuestionsSettings/index.tsx
- src/screens/CreateTest/TestSettings.tsx
- src/screens/Main/Main.tsx
- src/theme/colors.ts
> feat: displaying modal when switching to a new question

- __tests__/App-test.tsx
- i18n.js
- index.js
- package-lock.json
- package.json
- public/locales/en.json
- public/locales/ru.json
- src/components/AddingAnswer/index.tsx
- src/components/DraggableBottomSheet/Content/index.tsx
- src/components/DraggableBottomSheet/index.tsx
- src/components/FormSignIn/index.tsx
- src/components/Header/index.tsx
- src/components/ui/CustomTextInput/styles.ts
- src/components/ui/ReadyStyles/Boxes/index.ts
- src/components/ui/SmallButton/index.tsx
- src/components/ui/SmallButton/styles.ts
- src/navigation/TabButton/TabButton.tsx
- src/screens/CreateTest/CreateQuestion/CreateAnswer/index.tsx
- src/screens/CreateTest/CreateQuestion/index.tsx
- src/screens/CreateTest/TestSettings.tsx
- src/screens/Main/Main.tsx
Set up i18n, add localization on "Create test" screen.
> Setup i18n

- src/bll/resultReducer.ts
- src/components/IncorrectAnswers/index.tsx
- src/components/IncorrectAnswers/styles.ts
- tsconfig.json
> fix: IncorrectAnswers

- src/components/Tabs/Tab/index.tsx
- src/components/Tabs/Tab/styles.ts
- src/components/Tabs/Tab/tests/tab.test.tsx
- src/components/Tabs/index.tsx
- src/components/Tabs/styles.ts
- src/components/Tabs/tests/tabs.test.tsx
- src/components/ui/Loader/index.tsx
- src/customTypes/quiz-types.ts
- src/dal/questionsAPI.ts
- src/screens/CreateQuiz/components/CreateQuestion/CreateQuestionContainer.tsx
- src/screens/CreateQuiz/components/CreateQuestion/styles.ts
- src/screens/CreateQuiz/components/ListQuestions/Header/index.tsx
- src/screens/CreateQuiz/components/ListQuestions/ListQuestions.tsx
- src/screens/CreateQuiz/components/ListQuestions/ListQuestionsContainer.tsx
- src/screens/CreateQuiz/components/ListQuestions/ListingQuestions/ListingQuestions.tsx
- src/screens/CreateQuiz/components/ListQuestions/TabsQuestions/index.tsx
- src/screens/CreateQuiz/components/QuestionsSettings/QuestionsSettings.tsx
- src/screens/CreateQuiz/components/QuestionsSettings/styles.ts
- src/screens/CreateQuiz/services/services.ts
- src/screens/CreateQuiz/utils/getNewQuestion.ts
- src/screens/Testing/components/TestsList/TestsList.tsx
- src/theme/colors.ts
- src/utils/transformTime.ts
- Add filter questions for topic 
- Add functionality adding a question to a quiz
> add filter for topic and add functionality adding a question to a quiz

- App.tsx
- src/components/QuestionsTabs/index.tsx
- src/screens/CreateQuiz/components/CreateQuestion/CreateQuestion.tsx
- src/screens/CreateQuiz/components/CreateQuestion/CreateQuestionContainer.tsx
- src/screens/CreateQuiz/components/CreateQuestion/styles.ts
- src/screens/CreateQuiz/components/ListQuestions/Header/index.tsx
- src/screens/CreateQuiz/components/QuestionsSettings/ExitButton/index.tsx
- src/screens/CreateQuiz/components/QuestionsSettings/QuestionsSettings.tsx
- src/theme/colors.ts
- add blocking the editing of a created question
- add button for exit screen "Create Quiz"
> Block change question

- public/locales/en.json
- public/locales/ru.json
- src/components/MemoryCardsList/index.tsx
- src/components/MyQuizzes/index.tsx
- src/components/SelectAndCreateTopic/SelectAndCreateTopic.tsx
- src/components/SwitchSelectors/index.tsx
- src/components/SwitchSelectors/tests/SwitchSelectors.test.tsx
- src/components/SwitchSelectorsHookForm/index.tsx
- src/customTypes/SwitchSelectjrs-types.ts
- src/screens/CreateQuiz/components/CreateQuestion/CreateAnswer/index.tsx
- src/screens/CreateQuiz/components/CreateQuestion/CreateQuestion.tsx
- src/screens/CreateQuiz/components/ListQuestions/Header/index.tsx
- src/screens/CreateQuiz/components/QuestionsSettings/QuestionsSettings.tsx
- src/screens/CreateQuiz/components/QuizSettings/QuizSettings.tsx
- src/screens/CreateQuiz/components/QuizSettings/QuizSettingsContainer.tsx
- src/screens/Main/Main/Main.tsx
- src/screens/Testing/components/TestsList/TestsList.tsx
- src/utils/TransformLocalizationLanguage.ts
Added localization for profile and create quiz screens
> Localization profile&create quiz

- public/locales/en.json
- public/locales/ru.json
- src/bll/appReducer.ts
- src/components/DraggableBottomSheet/index.tsx
- src/components/MemoryCardsList/index.tsx
- src/components/MyQuizzes/index.tsx
- src/components/SelectAndCreateTopic/SelectAndCreateTopic.tsx
- src/components/SwitchSelectors/index.tsx
- src/components/SwitchSelectors/tests/SwitchSelectors.test.tsx
- src/components/SwitchSelectorsHookForm/index.tsx
- src/components/ui/ReadyStyles/Containers/index.ts
- src/customTypes/SwitchSelectjrs-types.ts
- src/navigation/navigation.tsx
- src/screens/CreateQuiz/components/CreateQuestion/CreateAnswer/index.tsx
- src/screens/CreateQuiz/components/CreateQuestion/CreateQuestion.tsx
- src/screens/CreateQuiz/components/CreateQuestion/CreateQuestionContainer.tsx
- src/screens/CreateQuiz/components/CreateQuestion/styles.ts
- src/screens/CreateQuiz/components/ListQuestions/Header/index.tsx
- src/screens/CreateQuiz/components/ListQuestions/ListingQuestions/ListingQuestions.tsx
- src/screens/CreateQuiz/components/QuestionsSettings/QuestionsSettings.tsx
- src/screens/CreateQuiz/components/QuizSettings/QuizSettings.tsx
- src/screens/CreateQuiz/components/QuizSettings/QuizSettingsContainer.tsx
- src/screens/CreateQuiz/index.tsx
- src/screens/Main/Main/Main.tsx
- src/screens/Testing/components/TestsList/TestsList.tsx
- src/utils/TransformLocalizationLanguage.ts
Fixed bug opening bottom sheet, added scroll  control
> Fix scroll bug

- src/screens/CreateQuiz/components/CreateQuestion/CreateQuestion.tsx
- src/screens/CreateQuiz/components/QuestionsSettings/QuestionsSettings.tsx
Optimizing component rendering "Question Setting" and child
> Rendering optimization

- src/bll/appReducer.ts
- src/bll/authReducer.ts
- src/screens/CreateQuiz/services/services.ts
- src/utils/requestMessageHandler.ts
> feat: request message handler

- public/locales/en.json
- public/locales/ru.json
- src/components/Form/FormButtons/index.tsx
- src/components/Form/FormSignIn/index.tsx
- src/components/Form/FormSignUp/index.tsx
- src/components/Header/styles.ts
- src/components/ui/ReadyStyles/Containers/index.ts
Added localization for login form and registration
> feat: localization login form

- src/bll/authReducer.ts
- src/components/CircularResultBar/index.tsx
- src/components/DraggableBottomSheet/styles.ts
- src/components/TestResult/index.tsx
- src/components/TestResult/styles.ts
- src/components/Timer/index.tsx
- src/customTypes/SmallButton-types.ts
- src/customTypes/navigation-types.ts
- src/screens/PassingQuiz/components/QuizList/index.tsx
- src/screens/PassingQuiz/components/QuizProcess/index.tsx
- src/screens/PassingQuiz/components/QuizResultScreen/index.tsx
- src/screens/PassingQuiz/index.tsx
- Add margin between control buttons
- Change size resultPage container
- Changed logic of the buttons in QuizResult screen: 
Press on "Close" -> redirection QuizList screen 
Press on "Try again" -> running passing the same quiz
- Changed list order in QuizList (reverse)
> Re-passing the test
